# -*- coding: utf-8 -*-
"""Obj_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15dGMLCtWwiWkn6wFzu67mB7hzFnk_OuU
"""

from google.colab import drive
drive.mount('/content/drive',force_remount=True)

!ls '/content/drive/My Drive/Dataset_Training'



!unzip '/content/drive/My Drive/Dataset_Training/Dataset.zip' -d '/content/drive/My Drive/Dataset_Training'

!git clone 'https://github.com/AlexeyAB/darknet.git' '/content/drive/My Drive/Dataset_Training/darknet'

# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/drive/My Drive/Dataset_Training/darknet'

!make

# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/drive/My Drive/Dataset_Training'

!python Dataset/creating-files-data-and-name.py

!python Dataset/creating-train-and-test-txt-files.py

!chmod +x darknet/darknet

!chmod +x /darknet/

pwd

!darknet/darknet detector train Dataset/labelled_data.data darknet/cfg/yolov3.cfg custom_weight/darknet53.conv.74 -dont_show